/* Included after the selected demo board: never edit generated sdk_config.h. */
#if AC7076A3_DEMO_ENABLE
/* Keep printf enabled; debug_uart_config.c substitutes a CDC log queue. */
#undef TCFG_DEBUG_UART_ENABLE
#define TCFG_DEBUG_UART_ENABLE 1
#undef TCFG_DEBUG_UART_TX_PIN
#define TCFG_DEBUG_UART_TX_PIN DEMO_UART_TX
#undef TCFG_DEBUG_UART_BAUDRATE
#define TCFG_DEBUG_UART_BAUDRATE DEMO_UART_BAUD
#undef TCFG_LOWPOWER_LOWPOWER_SEL
#define TCFG_LOWPOWER_LOWPOWER_SEL 0
#undef TCFG_ADKEY_ENABLE
#define TCFG_ADKEY_ENABLE 0
#undef TCFG_IOKEY_ENABLE
#define TCFG_IOKEY_ENABLE 0
#undef TCFG_CFG_TOOL_ENABLE
#define TCFG_CFG_TOOL_ENABLE 0
#undef TCFG_USB_CDC_BACKGROUND_RUN
#define TCFG_USB_CDC_BACKGROUND_RUN DEMO_USB_CDC_ENABLE
#undef TCFG_PC_ENABLE
#define TCFG_PC_ENABLE 0
#undef TCFG_TOUCH_PANEL_ENABLE
#define TCFG_TOUCH_PANEL_ENABLE 0 /* standalone CST816S; no CST816D FW upload */
#undef TCFG_TP_CST816D_ENABLE
#define TCFG_TP_CST816D_ENABLE 0
#undef TCFG_LCD_SPI_ST77916_ENABLE
#define TCFG_LCD_SPI_ST77916_ENABLE 0
#define TCFG_LCD_QSPI_JD9855_ENABLE 1
#undef TCFG_LCD_PIN_DC
#define TCFG_LCD_PIN_DC IO_PORTB_08
#undef TCFG_LCD_PIN_RESET
#define TCFG_LCD_PIN_RESET IO_PORTC_03
#undef TCFG_LCD_PIN_TE
#define TCFG_LCD_PIN_TE IO_PORTC_00
#undef TCFG_LCD_PIN_BL
#define TCFG_LCD_PIN_BL IO_LCD_PG
#undef TCFG_LCD_MATCH_MODE
#define TCFG_LCD_MATCH_MODE LCD_MATCH_BY_LOGO
#undef LCD_LOGO
#define LCD_LOGO "jd9855"
#undef TCFG_LCD_TE_USED_PEND
#define TCFG_LCD_TE_USED_PEND 0 /* no infinite wait on a missing TE signal */
#undef TCFG_LCD_TE_QUICK_SYNC
#define TCFG_LCD_TE_QUICK_SYNC 0
#undef TCFG_LCD_TP_USE_SAME_PWR
#define TCFG_LCD_TP_USE_SAME_PWR 0
#undef TP_POWER_DOWN_EN
#define TP_POWER_DOWN_EN 0
#undef LCD_POWER_DOWN_EN
#define LCD_POWER_DOWN_EN 0
#undef TCFG_TP_SLEEP_EN
#define TCFG_TP_SLEEP_EN 0
#undef TCFG_BACKLIGHT_PWM_MODE
#define TCFG_BACKLIGHT_PWM_MODE 0 /* demo uses the dedicated PG API itself */
#undef TCFG_ADC0_AIN_SEL
#define TCFG_ADC0_AIN_SEL 0 /* AUDIO_MIC0_CH0 = PA4 */
#undef TCFG_ADC0_BIAS_SEL
#define TCFG_ADC0_BIAS_SEL 1 /* AUDIO_MIC_BIAS_CH0 = PA4 */
#endif
