param(
    [ValidateSet('Configured', 'Basic', 'Screen', 'Audio', 'AudioUsb', 'Original')]
    [string]$Profile = 'Configured',
    [ValidateRange(1, 16)] [int]$Jobs = 8,
    [switch]$Download,
    [string]$KeyFile
)
$ErrorActionPreference = 'Stop'
$sdkDir = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$projectDir = Split-Path -Parent $sdkDir
$resultDir = Join-Path $projectDir 'output/bringup'
New-Item -ItemType Directory -Force -Path $resultDir | Out-Null
$makePath = Join-Path $sdkDir 'tools/utils/make.exe'
if (!(Test-Path -LiteralPath 'C:/JL/pi32/bin/clang.exe')) {
    throw 'Jieli toolchain is missing: C:/JL/pi32/bin/clang.exe'
}
$flags = switch ($Profile) {
    'Basic'    { '-DAC7076A3_DEMO_ENABLE=1 -DDEMO_MIC_ENABLE=0 -DDEMO_SPEAKER_ENABLE=0 -DDEMO_USB_CDC_ENABLE=0 -DDEMO_LCD_ENABLE=0' }
    'Screen'   { '-DAC7076A3_DEMO_ENABLE=1 -DDEMO_MIC_ENABLE=0 -DDEMO_SPEAKER_ENABLE=0 -DDEMO_USB_CDC_ENABLE=0 -DDEMO_LCD_ENABLE=1' }
    'Audio'    { '-DAC7076A3_DEMO_ENABLE=1 -DDEMO_MIC_ENABLE=1 -DDEMO_SPEAKER_ENABLE=1 -DDEMO_USB_CDC_ENABLE=0 -DDEMO_LCD_ENABLE=0' }
    'AudioUsb' { '-DAC7076A3_DEMO_ENABLE=1 -DDEMO_MIC_ENABLE=1 -DDEMO_SPEAKER_ENABLE=1 -DDEMO_USB_CDC_ENABLE=1 -DDEMO_LCD_ENABLE=0' }
    'Original' { '-DAC7076A3_DEMO_ENABLE=0' }
    default    { '' }
}
$logPath = Join-Path $resultDir ('build-' + $Profile + '.log')
$oldPath = $env:PATH
$oldDownloadPath = $env:PROJ_DOWNLOAD_PATH
$oldFormatVm = $env:FORMAT_VM_ENABLE
$oldFormatAll = $env:FORMAT_ALL_ENABLE
$oldKeyFilePath = $env:KEY_FILE_PATH
if ($Download -and $Profile -eq 'Original') {
    throw 'Original profile retains the 8 MiB watch resource layout; it cannot be burned to this 4 MiB board.'
}
Push-Location -LiteralPath $sdkDir
try {
    $env:PATH = (Join-Path $sdkDir 'tools/utils') + ';C:/JL/pi32/bin;' + $oldPath
    # -B matters: Make does not track command-line -D changes in object deps.
    # Windows PowerShell 5.1 represents native stderr as ErrorRecords, even
    # for linker warnings. Decide success from make's exit code instead.
    try {
        $ErrorActionPreference = 'Continue'
        & $makePath build-only -B "-j$Jobs" "EXT_CFLAGS=$flags" *> $logPath
        $buildExit = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = 'Stop'
    }
    Get-Content -LiteralPath $logPath -Tail 12
    if ($buildExit -ne 0) {
        throw "Build failed ($buildExit). Full log: $logPath"
    }
    $elf = Join-Path $sdkDir 'cpu/br35/tools/sdk.elf'
    $manifest = [ordered]@{
        profile = $Profile
        defines = $flags
        builtAt = (Get-Date).ToString('o')
        elf = $elf
        sha256 = (Get-FileHash -LiteralPath $elf -Algorithm SHA256).Hash
        bytes = (Get-Item -LiteralPath $elf).Length
        warningLines = @(Select-String -LiteralPath $logPath -Pattern 'warning:').Count
        hardwareValidated = $false
        log = $logPath
    }
    $manifest | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $resultDir 'last-build.json') -Encoding utf8
    $manifest | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $resultDir ('build-' + $Profile + '.json')) -Encoding utf8
    Write-Output "Build succeeded: $elf"
    if ($Download) {
        if ($KeyFile) {
            $resolvedKey = (Resolve-Path -LiteralPath $KeyFile).Path
            if (!(Test-Path -LiteralPath $resolvedKey -PathType Leaf) -or
                [IO.Path]::GetExtension($resolvedKey) -ine '.key') {
                throw 'KeyFile must be an existing Jieli .key file.'
            }
            if ($resolvedKey -notmatch '^[A-Za-z0-9_:.\\/-]+$') {
                throw 'The vendor batch requires a KEY path containing only ASCII letters, digits, _, -, ., : and backslash. Move the .key file to such a path.'
            }
            $env:KEY_FILE_PATH = $resolvedKey
        }
        $ini = Get-Content -LiteralPath (Join-Path $sdkDir 'cpu/br35/tools/isd_config.ini') -Raw
        if ($ini -match '(?m)^\s*(MODE_FILE|FATFSI_FILE)\s*=') {
            throw 'The generated INI still contains watch UI partitions; refusing to download it to a 4 MiB device.'
        }
        $generatedBatch = Get-Content -LiteralPath (Join-Path $sdkDir 'cpu/br35/tools/download.bat') -Raw
        if ($generatedBatch -notmatch 'call download/watch/download\.bat') {
            throw 'The generated download batch is not the resource-free 4 MiB demo path.'
        }
        # The user moved configuration resources into doc/. Copy missing files
        # only; never replace newer output/ resources generated by JLStudio.
        $resourceDir = Join-Path $projectDir 'output'
        foreach ($name in @('cfg_tool.bin', 'stream.bin')) {
            $dest = Join-Path $resourceDir $name
            if (!(Test-Path -LiteralPath $dest)) {
                $source = Join-Path $projectDir ('doc/' + $name)
                if (!(Test-Path -LiteralPath $source)) {
                    throw "Missing configuration resource: $name; export it with JLStudio."
                }
                Copy-Item -LiteralPath $source -Destination $dest
            }
        }
        # Vendor batch scripts interpolate this variable without quotes.
        if ($resourceDir.Contains(' ')) {
            throw 'Vendor download scripts need a project path without spaces.'
        }
        $env:PROJ_DOWNLOAD_PATH = $resourceDir
        $env:FORMAT_VM_ENABLE = ''
        $env:FORMAT_ALL_ENABLE = ''
        $downloadLog = Join-Path $resultDir ('download-' + $Profile + '.log')
        $downloadStart = Get-Date
        try {
            $ErrorActionPreference = 'Continue'
            & cmd.exe /d /c 'cpu\br35\tools\download.bat sdk' *> $downloadLog
            $downloadExit = $LASTEXITCODE
        } finally {
            $ErrorActionPreference = 'Stop'
        }
        Get-Content -LiteralPath $downloadLog -Tail 35
        if ($downloadExit -ne 0 -or @(Select-String -LiteralPath $downloadLog -Pattern '^\s*ERROR:').Count -gt 0) {
            # The vendor batch continues packaging after a failed device write.
            # Do not leave fresh, unusable copied firmware in output/.
            foreach ($name in @('update.ufw', 'jl_isd.bin', 'jl_isd.fw')) {
                $candidate = Join-Path $resourceDir $name
                if ((Test-Path -LiteralPath $candidate) -and
                    (Get-Item -LiteralPath $candidate).LastWriteTime -ge $downloadStart) {
                    Remove-Item -LiteralPath $candidate
                }
            }
            throw "Download failed; inspect the first error in $downloadLog"
        }
        Write-Output 'Check isd_download success and reboot logs; a batch exit code alone is not burn verification.'
    }
} finally {
    Pop-Location
    $env:PATH = $oldPath
    $env:PROJ_DOWNLOAD_PATH = $oldDownloadPath
    $env:FORMAT_VM_ENABLE = $oldFormatVm
    $env:FORMAT_ALL_ENABLE = $oldFormatAll
    $env:KEY_FILE_PATH = $oldKeyFilePath
}
